# Generated by Django 6.0 on 2025-12-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('input_cost', models.DecimalField(decimal_places=2, help_text='Cost per million input tokens', max_digits=10)),
                ('cached_input_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per million cached input tokens', max_digits=10, null=True)),
                ('output_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per million output tokens', max_digits=10, null=True)),
            ],
        ),
    ]
