# Generated by Django 6.0 on 2025-12-08 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openaimodel',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this model', related_name='assigned_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
