# Generated by Django 6.0 on 2025-12-08 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_openaimodel_assigned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaimodel',
            options={'ordering': ['name'], 'verbose_name': 'OpenAI Model', 'verbose_name_plural': 'OpenAI Models'},
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this model for summarization', related_name='assigned_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='cached_input_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost per million cached input tokens in USD (optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='input_cost',
            field=models.DecimalField(decimal_places=6, help_text='Cost per million input tokens in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='name',
            field=models.CharField(help_text="The OpenAI model identifier (e.g., 'gpt-3.5-turbo', 'gpt-4')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='output_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cost per million output tokens in USD (optional)', max_digits=10, null=True),
        ),
    ]
