# Generated by Django 6.0 on 2025-12-09 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_openaimodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIModel',
            new_name='SupportedOpenAIModel',
        ),
    ]
